import { HttpHeaders } from '@angular/common/http';

export const URL_END_POINT_BASE = 'http://localhost:8080';
export const CREDENCIALES = btoa('sistemagestionriesgo' + ':' + '12345');

// Variable para la cabecera de una solicitud de token
export const HTTP_HEADERS_TOKEN = new HttpHeaders({
    'Content-Type': 'application/x-www-form-urlencoded',
    Authorization: 'Basic ' + CREDENCIALES
});

export const CODIGO_PARAMETRO_PERIODO = 'TTP0000';
export const CODIGO_PARAMETRO_ANIO = 'AN0000';
export const CODIGO_PARAMETRO_FREC = 'FREP0000';
export const CODIGO_PARAMETRO_OPERADORES = 'TTO0000';
export const CODIGO_PARAMETRO_ESTADO = 'EPO0000';
export const CODIGO_PARAMETRO_MATRIZ = 'MATR0000';
export const CODIGO_PARAMETRO_MATRIZ_FRAUDE = 'MATF0000';
export const CODIGO_PARAMETRO_TIPO_MATRIZ = 'TMATR0000';
export const CODIGO_PARAMETRO_CARTERA = 'CART0000';
export const CODIGO_PARAMETRO_RESPONSABILIDAD = 'TRESP0000';
export const CODIGO_PARAMETRO_CARGO = 'CARG0000';
export const CODIGO_PARAMETRO_NIVEL_RIESGOS = 'RIES0000';
export const CODIGO_PARAMETRO_TIPO_PREGUNTA = 'PREG0000';
export const CODIGO_PARAMETRO_GRUPO_PREGUNTA = 'GRUP0000';

export const CODIGO_PARAMETRO_ORIGEN_RIESGO = 'ORIG0000';
export const CODIGO_PARAMETRO_FRECUENCIA_RIESGO = 'FRIESG0000';
export const CODIGO_PARAMETRO_TIPO_RIESGO = 'TRIESG0000';
export const CODIGO_PARAMETRO_TIPO_RIESGO_MA = 'TIMA0000';
export const CODIGO_PARAMETRO_TIPO_RIESGOF = 'TRIESF0000';
export const CODIGO_PARAMETRO_AREA_RESPONSABLE = 'ARESP0000';
export const CODIGO_PARAMETRO_RESPONSABLE_CONTROL = 'RESPC0000';
export const CODIGO_PARAMETRO_FRECUENCIA_CONTROL = 'FCONT0000';
export const CODIGO_PARAMETRO_OPORTUNIDAD_CONTROL = 'OPOR0000';
export const CODIGO_PARAMETRO_AUTOMATIZACION_CONTROL = 'AUTO0000';
export const CODIGO_PARAMETRO_ESTADO_PLAN_ACCION = 'ESPLA0000';
export const CODIGO_PARAMETRO_ESTADO_PLAN_MF = 'ESMF0000';
export const CODIGO_PARAMETRO_EFICAZ_PLAN_ACCION = 'PLACC0000';
export const CODIGO_PARAMETRO_ESTRATEGIA_PLAN_ACCION = 'ESTP0000';
export const CODIGO_PARAMETRO_EFECTIVIDAD = 'EFEC0000';
export const CODIGO_PARAMETRO_INDICADOR_SI_NO = 'INDI0000';
export const CODIGO_PARAMETRO_INDICADOR_SELECCION_SINO = 'INDI0000';
export const CODIGO_PARAMETRO_ESTRATEGIA_RESPUESTA = 'ESTP0000';
export const CODIGO_PARAMETRO_ESTRATEGIA_MA = 'ESMA0000';
export const CODIGO_PARAMETRO_ESTRATEGIA_OPOR = 'ESTRA0000';
export const CODIGO_PARAMETRO_TIPO_BENEFICIO = 'TBENE0000';


export const CODIGO_PARAMETRO_TIPO_DELITO = 'TIPD0000';
export const CODIGO_PARAMETRO_APLICA_DEBIDA_DILIGENCIA = 'DEBD0000';
export const CODIGO_PARAMETRO_INDICADOR_FIN_PLAN_ACCION = 'INFP0000';
export const CODIGO_PARAMETRO_EFICACIA_CONTROLES_ACTUALES = 'EFCA0000';


export const CODIGO_PARAMETRO_ESTADO_EVENTO = 'ESTE0000';
export const CODIGO_PARAMETRO_CUENTA_PLAN_ACCION = 'CPLA0000';

export const CODIGO_PARAMETRO_COLOR_VELOCIMETRO = 'COLOR000';

export const CODIGO_CANTIDAD_CONTROL = 'CPLUS000';

export const MATRIZ_OPERACIONAL = 40;
export const MATRIZ_FRAUDE = 41;
export const MATRIZ_CONTINUIDAD = 45;
export const MATRIZ_OPORTUNIDAD = 42;
export const MATRIZ_ANTICORRUPCION = 73;
export const MATRIZ_EVENTO = 83;